### ISSUE TITLE
Добавь интерфейс WPF

### ISSUE THREAD

**Issue by Slavamk3dell** [VeryLazyCoder/Brodilka#4]
Если ты это не сделаешь, тебя покарает Мымрина. Даю тебе 5 минут
<img width="381" alt="Снимок экрана 2023-04-18 110725" src="https://github.com/VeryLazyCoder/Brodilka/assets/63102871/1bc9e321-cd64-4e83-8564-0c647f2fc326">

**Comment by VeryLazyCoder** [comment]
А не пойти ли тебе нахер?
